name: 2025.1.x
on:
  push:
    branches: [ main, xuxiaowei/* ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        spring-cloud-version: [ 2025.1.0, 2025.1.1, 2025.1.2 ]
        spring-cloud-build-version: [ 5.0.0, 5.0.1, 5.0.2 ]
        spring-boot-version: [ 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.1.0 ]
    env:
      BRANCH: 2025.1.x
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Dependencies Cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Clone alibaba/spring-cloud-alibaba ${{ env.BRANCH }}
        run: git clone --branch ${{ env.BRANCH }} --depth 1 https://github.com/alibaba/spring-cloud-alibaba
      - name: Print Maven version
        working-directory: spring-cloud-alibaba
        run: ./mvnw -version
      - name: Set spring-cloud-build version
        working-directory: spring-cloud-alibaba
        run: |
          sed -i "s#<version>5.0.0</version>#<version>${{ matrix.spring-cloud-build-version }}</version>#" pom.xml
          sed -i "s#<version>5.0.0</version>#<version>${{ matrix.spring-cloud-build-version }}</version>#" spring-cloud-alibaba-dependencies/pom.xml
      - name: Compile & Checkstyle
        working-directory: spring-cloud-alibaba
        run: ./mvnw clean -B -T 1C compile -Dspring-boot.version=${{ matrix.spring-boot-version }} -Dspring.cloud.version=${{ matrix.spring-cloud-version }}
      - name: install dependencies
        working-directory: spring-cloud-alibaba
        run: ./mvnw -B -T 1C install -U package -pl '!spring-cloud-alibaba-coverage' -DskipTests -Dspring-boot.version=${{ matrix.spring-boot-version }} -Dspring.cloud.version=${{ matrix.spring-cloud-version }}
      - name: Testing
        working-directory: spring-cloud-alibaba
        run: ./mvnw verify -B -T 1C -Dmaven.test.skip=false -Dspring-boot.version=${{ matrix.spring-boot-version }} -Dspring.cloud.version=${{ matrix.spring-cloud-version }}
      - name: Delete snapshots from the Maven local repository
        run: find ~/.m2/repository -type d -name '*-SNAPSHOT' -print -exec rm -r {} +
